"""Condensed original study curriculum aligned to the user's 20-chapter STC SIE manual.
The wording below is original paraphrase for study use; it does not reproduce the manual.
"""

CHAPTERS = {
1:{"title":"Market Participants & Market Structure","section":"Capital Markets","cards":[
("Issuer","Legal entity that raises capital by selling debt or equity securities."),("Broker","Acts as agent for others and is generally compensated by commission."),("Dealer","Acts as principal for its own account and may earn a markup or markdown."),("Market Maker","Broker-dealer that displays two-sided quotations and stands ready to buy and sell."),("Bid","Price at which a market maker is willing to buy."),("Ask / Offer","Price at which a market maker is willing to sell."),("Primary Market","Market in which newly issued securities are sold and the issuer receives proceeds."),("Secondary Market","Market in which outstanding securities trade among investors."),("Third Market","Exchange-listed securities trading over-the-counter or away from the listing exchange."),("Fourth Market","Direct institution-to-institution trading."),("DTCC","Industry-owned infrastructure that centralizes clearing and settlement for many securities."),("NSCC vs FICC","NSCC clears many equity trades; FICC clears fixed-income trades."),("OCC","Clearing corporation that issues and guarantees listed options."),("Introducing Firm","Broker-dealer that relies on a carrying/clearing firm for back-office clearing functions."),("QIB","Eligible institution generally owning/investing at least $100 million in unaffiliated securities; individuals are not QIBs.")]},
2:{"title":"Overview of Regulation","section":"Capital Markets","cards":[
("SEC","Federal securities regulator responsible for investor protection, orderly markets and capital formation."),("FINRA","Primary self-regulatory organization for broker-dealers and associated persons."),("MSRB","Writes rules for municipal securities dealers and municipal advisors; enforcement is handled by other regulators."),("NASAA","Association of state securities administrators; associated with state blue-sky regulation."),("Securities Act of 1933","Focuses on new issues, primary-market disclosure and prospectuses."),("Securities Exchange Act of 1934","Created the SEC and regulates secondary trading, antifraud activity and margin framework."),("Investment Advisers Act of 1940","Regulates investment advisers; classic definition uses Advice, Business and Compensation."),("Investment Company Act of 1940","Regulates registered investment companies such as mutual funds."),("SIPA / SIPC","Protects qualifying customer assets when a member broker-dealer fails; does not cover market loss."),("SIPC Limits","Generally $500,000 per separate customer, including a $250,000 cash sublimit."),("TCPA","Restricts solicitation calls and supports do-not-call protections; calls generally limited to 8 a.m. to 9 p.m. local time."),("USA PATRIOT Act","Strengthened AML, customer identification and suspicious-activity reporting requirements."),("Code of Procedure","FINRA disciplinary process for rule violations."),("Code of Arbitration","Forum used to resolve monetary disputes among members, associated persons and customers."),("Written Supervisory Procedures","Firm-specific supervisory manual identifying policies, responsibilities and controls.")]},
3:{"title":"Equity Securities","section":"Products & Risks","cards":[
("Common Stock","Basic corporate ownership interest; generally last in liquidation priority."),("Preferred Stock","Equity security with dividend and liquidation preference over common stock but below debt."),("Authorized Shares","Maximum shares permitted by the corporate charter."),("Issued Shares","Shares that the corporation has actually sold or distributed."),("Treasury Stock","Previously issued shares repurchased by the issuer; no voting rights or dividends while held in treasury."),("Outstanding Shares","Issued shares minus treasury shares; these shares generally vote and receive dividends."),("Limited Liability","Shareholder loss is generally limited to the amount invested."),("Preemptive Right","Right that may let existing common shareholders maintain proportionate ownership in a new issue."),("Warrant","Longer-term issuer-created right to buy stock at a stated price."),("Rule 144","Rule governing resales of restricted and control securities subject to conditions."),("Cumulative Preferred","Missed preferred dividends accumulate and must be paid before common dividends."),("Convertible Preferred","Preferred stock exchangeable into common shares under stated terms."),("ADR","Receipt representing ownership in shares of a foreign issuer and trading in U.S. markets."),("Growth Stock","Stock selected primarily for capital appreciation potential."),("Income Stock","Stock selected primarily for dividend income.")]},
4:{"title":"Introduction to Debt Instruments","section":"Products & Risks","cards":[
("Par Value","Face amount repaid at maturity, commonly $1,000 for corporate bonds."),("Coupon Rate","Stated annual interest rate applied to par value."),("Current Yield","Annual interest divided by current market price."),("Yield to Maturity","Return measure assuming the bond is held to maturity and promised payments are made."),("Premium Bond","Bond trading above par."),("Discount Bond","Bond trading below par."),("Price-Yield Relationship","Bond prices generally move inversely to market interest rates and yields."),("Interest-Rate Risk","Risk that bond prices change when market rates change; generally greater for longer maturities."),("Credit Risk","Risk that the issuer cannot meet interest or principal obligations."),("Call Provision","Allows issuer to redeem debt before maturity under stated terms."),("Call Protection","Period during which a callable bond cannot be called."),("Put Provision","Allows investor to sell the bond back to issuer under stated terms."),("Conversion Ratio","Number of common shares received when a convertible bond is converted; based on par divided by conversion price."),("Accrued Interest","Interest earned since the last coupon date and owed by buyer to seller on many bond trades."),("Basis Point","One one-hundredth of one percent, or 0.01%.")]},
5:{"title":"Types of Debt Instruments","section":"Products & Risks","cards":[
("Treasury Bill","Short-term U.S. government obligation sold at a discount and maturing in one year or less."),("Treasury Note","U.S. Treasury debt generally issued with intermediate maturities."),("Treasury Bond","Long-term direct U.S. government debt obligation."),("TIPS","Treasury security designed to provide inflation protection through principal adjustment."),("GNMA","Government agency whose mortgage-backed securities carry explicit U.S. government backing."),("FNMA / FHLMC","Government-sponsored enterprises active in mortgage markets; not direct Treasury obligations."),("Prepayment Risk","Risk that mortgage borrowers repay early, especially when rates fall, forcing reinvestment at lower yields."),("GO Municipal Bond","Municipal debt backed primarily by the issuer's taxing power."),("Revenue Bond","Municipal debt backed primarily by revenue from a project or facility."),("Municipal Note","Short-term municipal borrowing instrument."),("Debenture","Unsecured corporate bond backed by the issuer's general credit."),("Secured Bond","Corporate debt backed by pledged collateral."),("Commercial Paper","Unsecured short-term corporate money-market debt."),("Banker's Acceptance","Time draft commonly used to finance international trade."),("Negotiable CD","Large-denomination bank certificate of deposit that may trade in the secondary market.")]},
6:{"title":"Investment Returns","section":"Trading, Accounts & Prohibited Activities","cards":[
("Ex-Dividend Date","Date on and after which a buyer is not entitled to the upcoming declared dividend."),("Record Date","Date on which the issuer identifies shareholders entitled to a declared dividend."),("Stock Dividend","Distribution of additional shares; generally adjusts price and cost basis rather than creating immediate taxable cash income."),("Nominal Yield","Bond coupon rate stated as a percentage of par."),("Current Yield Formula","Annual bond interest divided by current market price."),("Premium Yield Relationship","For a premium bond, coupon rate is generally above current yield, which is above YTM."),("Discount Yield Relationship","For a discount bond, coupon rate is generally below current yield, which is below YTM."),("Capital Gain","Sales proceeds exceed adjusted cost basis."),("Capital Loss","Sales proceeds are below adjusted cost basis."),("Total Return","Income plus realized/unrealized change in value over the measurement period, expressed relative to investment."),("Basis Point","0.01%; 100 basis points equals 1%."),("S&P 500","Broad capitalization-weighted index of large U.S. companies."),("DJIA","Price-weighted index of 30 large U.S. companies."),("Broad-Based Index","Index representing a wide market segment."),("Narrow-Based Index","Index focused on a limited sector or industry.")]},
7:{"title":"Packaged Products","section":"Products & Risks","cards":[
("Open-End Fund","Mutual fund that continuously issues and redeems shares with transactions based on NAV."),("Closed-End Fund","Investment company with a fixed share base whose shares trade in the secondary market."),("UIT","Investment company with a generally fixed portfolio and no active investment adviser managing day-to-day selections."),("NAV","Fund assets minus liabilities divided by shares outstanding."),("POP","Public offering price paid by investor; for a load fund it may equal NAV plus sales charge."),("Forward Pricing","Mutual fund orders execute at the next calculated NAV after receipt in good order."),("12b-1 Fee","Asset-based distribution/marketing fee charged by some mutual funds."),("Class A Shares","Often impose a front-end sales charge with lower ongoing distribution fees than other load classes."),("Class C Shares","Often have no large front-end load but higher ongoing distribution expenses and possible short-term CDSC."),("Breakpoint","Reduced Class A sales charge available at higher investment levels."),("Letter of Intent","Allows investor to qualify for breakpoints based on intended purchases over a specified period."),("Rights of Accumulation","Uses existing eligible holdings plus new purchase to determine breakpoint eligibility."),("Dollar-Cost Averaging","Investing equal dollar amounts at regular intervals; does not assure profit or protect against loss."),("Breakpoint Sale","Improper practice of recommending a purchase just below a breakpoint to generate a higher sales charge."),("Switching","Potentially improper excessive movement between mutual funds that generates unnecessary sales charges.")]},
8:{"title":"Variable Contracts & Municipal Fund Securities","section":"Products & Risks","cards":[
("Fixed Annuity","Insurance contract in which insurer generally bears investment risk and promises stated guarantees."),("Variable Annuity","Insurance contract whose separate-account performance causes contract value to fluctuate; owner bears investment risk."),("General Account","Insurer account supporting fixed guarantees; assets belong to insurer."),("Separate Account","Segregated account supporting variable products and generally registered as an investment company."),("Accumulation Phase","Period before annuitization when units are accumulated and values may grow tax-deferred."),("Annuity Phase","Period after annuitization when accumulation units are converted to annuity units and payments begin."),("Annuitant","Person whose life expectancy is used to determine certain annuity benefits."),("Contract Owner","Person who controls contractual rights and typically makes investment decisions."),("Beneficiary","Person designated to receive death benefits under the contract."),("Qualified Annuity","Annuity held in a tax-qualified retirement arrangement; contributions may receive retirement-plan tax treatment."),("Nonqualified Annuity","Annuity funded with after-tax dollars; earnings grow tax-deferred."),("1035 Exchange","Tax-deferred exchange permitted among certain insurance and annuity contracts if requirements are satisfied."),("529 Plan","State-sponsored municipal fund security designed primarily for qualified education expenses."),("ABLE / 529A","Tax-advantaged account designed for eligible individuals with disabilities."),("LGIP","Local government investment pool used by governmental entities to invest short-term funds.")]},
9:{"title":"Alternative Investments","section":"Products & Risks","cards":[
("ETF","Exchange-traded pooled product whose shares trade intraday at market prices."),("Leveraged ETF","ETF designed to deliver a multiple of an index's DAILY return; compounding can create path-dependent results."),("Inverse ETF","ETF designed to move opposite an index's DAILY performance."),("ETN","Unsecured debt obligation whose return is linked to an index or benchmark; investor bears issuer credit risk."),("Hedge Fund","Private pooled fund often using flexible, sophisticated or leveraged strategies."),("REIT","Company/trust investing in income-producing real estate or real-estate financing."),("Equity REIT","REIT that primarily owns and operates properties."),("Mortgage REIT","REIT that primarily invests in mortgages or mortgage-related debt."),("DPP","Direct participation structure that may pass income, gains, losses and deductions through to investors."),("Limited Partnership","DPP structure with a general partner managing the business and limited partners supplying capital."),("General Partner","Manages partnership and generally has unlimited liability."),("Limited Partner","Passive investor whose liability is generally limited to investment if limited-partner status is preserved."),("Flow-Through Taxation","Partnership tax concept under which results pass through to partners rather than being taxed at the partnership level."),("Liquidity Risk","Risk that an investment cannot be sold quickly at a fair price; common concern in alternatives."),("Credit Risk in ETNs","Because an ETN is unsecured debt, the issuer's creditworthiness is central.")]},
10:{"title":"Options","section":"Products & Risks","cards":[
("Call Buyer","Has the right to buy the underlying at the strike price; generally bullish."),("Put Buyer","Has the right to sell the underlying at the strike price; generally bearish."),("Option Writer","Has an obligation if assigned and receives the premium."),("Call In the Money","Underlying market price is above the call strike price."),("Put In the Money","Underlying market price is below the put strike price."),("Intrinsic Value","Amount an option is in the money; never negative."),("Time Value","Premium minus intrinsic value."),("Long Call Breakeven","Strike price plus premium paid."),("Long Put Breakeven","Strike price minus premium paid."),("Option Buyer Max Loss","Premium paid."),("Uncovered Call","Short call without owning the underlying stock; potentially unlimited loss."),("Covered Call","Long stock combined with a short call on the same underlying."),("Protective Put","Long stock combined with a long put to establish downside protection."),("Bullish Positions","Long calls and short puts are directionally bullish."),("Bearish Positions","Long puts and short calls are directionally bearish.")]},
11:{"title":"Offerings","section":"Capital Markets","cards":[
("IPO","Issuer's first public offering of securities."),("Follow-On Offering","Additional public issuance by a company already public."),("Firm Commitment","Underwriter buys the issue from the issuer and assumes resale risk."),("Best Efforts","Underwriter acts as agent and sells as much of the issue as possible without guaranteeing full sale."),("All-or-None","Best-efforts arrangement requiring the entire offering to be sold or the deal is cancelled."),("Syndicate","Group of underwriters that shares responsibility and risk in distributing an offering."),("Selling Group","Dealers that help sell the issue but generally do not share underwriting liability."),("Underwriting Spread","Difference between public offering price and amount received by issuer."),("Registration Statement","SEC filing containing required information about issuer and offering."),("Cooling-Off Period","Period after registration filing and before effectiveness when sales are restricted and indications of interest may be gathered."),("Red Herring","Preliminary prospectus used during the cooling-off period; omits final price/effective information."),("Statutory Prospectus","Final prospectus containing required offering information."),("Regulation D","Private-offering safe harbor with exemptions from full SEC registration under specified conditions."),("Rule 144A","Facilitates resales of certain restricted securities to QIBs."),("EMMA","MSRB electronic system providing municipal disclosure and trade information.")]},
12:{"title":"Orders & Trading Strategies","section":"Trading, Accounts & Prohibited Activities","cards":[
("Agent Capacity","Broker acts for a customer and generally charges commission."),("Principal Capacity","Dealer trades with customer for its own account and may use markup/markdown."),("5% Policy","FINRA fairness guideline; not a fixed maximum and depends on transaction facts."),("Long Sale","Sale of securities owned by the seller."),("Short Sale","Sale of borrowed securities by an investor expecting a price decline."),("Market Order","Prioritizes execution at the best available price; price is not guaranteed."),("Buy Limit","May execute at the limit price or lower."),("Sell Limit","May execute at the limit price or higher."),("Buy Stop","Placed above current market and commonly used to protect a short position or enter on an upside breakout."),("Sell Stop","Placed below current market and commonly used to protect a long position."),("Stop Order","Becomes a market order once triggered."),("Stop-Limit Order","Becomes a limit order once triggered; execution is not guaranteed."),("Day Order","Expires at the end of the trading day if not executed."),("GTC Order","Remains open until executed, cancelled or expired under firm policy."),("Not-Held Order","Allows time and/or price discretion for execution without giving broader account discretion.")]},
13:{"title":"Settlement & Corporate Actions","section":"Trading, Accounts & Prohibited Activities","cards":[
("Regular-Way Equity Settlement","Most U.S. equity trades settle T+1 under the current settlement cycle."),("Cash Settlement","Same-day settlement by agreement."),("Good Delivery","Delivery that satisfies industry requirements for transfer of securities."),("Stock Power","Separate form that may be used to endorse transfer of a physical certificate."),("Forward Split","Increases shares and proportionally decreases price; total market value is initially unchanged."),("Reverse Split","Decreases shares and proportionally increases price; total market value is initially unchanged."),("Tender Offer","Public offer to purchase shares, often at a stated price and for a limited period."),("Record Date","Issuer date for identifying holders entitled to a corporate distribution."),("Ex-Date","Trading date on and after which buyer generally does not receive the upcoming distribution."),("Proxy","Authorization permitting another party to vote shares."),("Street Name","Securities registered in broker-dealer name while beneficial ownership belongs to customer."),("Book-Entry","Electronic ownership record rather than physical certificate."),("Settlement Date","Date buyer pays and seller delivers securities."),("Due Bill","Document used when a distribution belongs to the buyer despite record-date mechanics."),("Corporate Action","Issuer event such as dividend, split, merger, tender or rights distribution that can affect security holders.")]},
14:{"title":"Customer Accounts","section":"Trading, Accounts & Prohibited Activities","cards":[
("Cash Account","Customer pays in full; no broker-dealer credit is used to finance purchases."),("Margin Account","Customer may borrow from broker-dealer, subject to Regulation T and maintenance requirements."),("Options Account","Requires specific approval and delivery of required options disclosure before or at approval."),("Discretionary Account","Representative may exercise authorized discretion after written customer authorization and firm approval."),("Time/Price Discretion","Limited discretion over timing or price of an order; generally does not require full discretionary-account authorization."),("Individual Account","Account owned by one person."),("Joint Tenants with Rights of Survivorship","Joint ownership where deceased owner's interest passes to surviving owner(s)."),("Tenants in Common","Joint ownership in stated shares; deceased owner's interest passes through estate."),("UGMA/UTMA","Irrevocable custodial account for a minor; one custodian manages property for one minor."),("Traditional IRA","Retirement account with tax-deferred growth; deductibility and taxation depend on circumstances."),("Roth IRA","After-tax retirement account with potential tax-free qualified distributions."),("RMD","Required minimum distribution rules generally apply to traditional retirement accounts, not original Roth IRA owners."),("ERISA","Federal law governing many private-sector qualified retirement plans, including fiduciary and vesting standards."),("Coverdell ESA","Education savings account subject to eligibility and contribution rules."),("529 Plan","State-sponsored education savings program with tax advantages for qualified education expenses.")]},
15:{"title":"Compliance Considerations","section":"Trading, Accounts & Prohibited Activities","cards":[
("KYC","Know Your Customer obligation to use reasonable diligence to understand essential facts about a customer."),("Regulation Best Interest","Requires broker-dealer recommendations to retail customers to be in the customer's best interest without placing the firm's interest ahead."),("Customer Identification Program","AML procedure for obtaining and verifying customer identity."),("Placement","First stage of money laundering: introducing illicit funds into financial system."),("Layering","Second stage: moving funds through transactions to obscure origin."),("Integration","Final stage: reintroducing funds as apparently legitimate assets."),("CTR","Currency Transaction Report generally required for qualifying cash transactions exceeding $10,000."),("SAR","Suspicious Activity Report used to report qualifying suspicious transactions/activity to FinCEN."),("FinCEN","Treasury bureau administering and enforcing major AML reporting requirements."),("Regulation S-P","Privacy rule governing treatment and safeguarding of consumer financial information."),("Correspondence","Written/electronic communication distributed to 25 or fewer retail investors within 30 calendar days."),("Retail Communication","Communication distributed to more than 25 retail investors within 30 calendar days."),("Institutional Communication","Communication distributed or made available only to institutional investors and not intended for retail investors."),("BCP","Business Continuity Plan describing how the firm will continue critical operations after disruption."),("Trusted Contact","Person a firm may contact in specified situations concerning a customer's account, especially potential exploitation or inability to reach customer.")]},
16:{"title":"Prohibited Activities","section":"Trading, Accounts & Prohibited Activities","cards":[
("Churning","Excessive trading in a customer account primarily to generate compensation."),("Reverse Churning","Inappropriate placement of inactive customer in fee-based account where ongoing fees are not justified."),("Front-Running","Improperly trading ahead of a customer order to benefit from expected market impact."),("Trading Ahead of Research","Improper proprietary or personal trading before publication of material research under applicable rules."),("Marking the Close","Trading near market close to manipulate closing price."),("Interpositioning","Improper insertion of an unnecessary third party between customer and market."),("Insider Trading","Trading while in possession of material nonpublic information in violation of applicable duties/law."),("Material Information","Information a reasonable investor would consider important in making an investment decision."),("New Issue Rule","FINRA rule restricting certain industry insiders/restricted persons from purchasing new equity IPO shares."),("Guarantee Against Loss","Registered persons may not guarantee customers against securities investment losses."),("Sharing in Customer Account","Restricted; requires applicable approvals and generally proportional sharing based on contribution, subject to exceptions."),("Borrowing/Lending with Customer","Restricted and permitted only in specified relationships/conditions under firm procedures."),("FINRA Rule 2165","Allows temporary holds in specified situations involving suspected financial exploitation of certain adults."),("Freeriding","Generally buying securities and selling them before paying for the purchase in a cash account."),("Best Execution","Firm duty to use reasonable diligence to seek the most favorable terms reasonably available for a customer order.")]},
17:{"title":"SRO Requirements for Associated Persons","section":"Regulatory Framework","cards":[
("Associated Person","Employee or other covered person associated with a broker-dealer, whether registered or unregistered."),("SIE","Corequisite knowledge exam; passing alone does not authorize securities business without appropriate registration and firm association."),("Representative","Registered person permitted to conduct specified customer-facing securities activities."),("Principal","Registered person with supervisory or management responsibilities."),("Form U4","Registration application and disclosure form for associated persons."),("CRD","Central Registration Depository system containing licensing and disclosure records."),("Statutory Disqualification","Specified event that may bar association unless eligibility relief is granted."),("Fingerprinting","Required for many associated persons to support background checks, subject to limited exceptions."),("Blue-Sky Registration","State securities registration framework for firms, agents and securities."),("Regulatory Element","FINRA continuing-education component for registered persons."),("Firm Element","Annual firm-designed continuing education based on training needs."),("MQP","Maintaining Qualifications Program allowing eligible terminated registrants to preserve qualifications by meeting conditions."),("Exam Confidentiality","Candidates may not reproduce, disclose or solicit live exam content."),("Unregistered Personnel","May perform clerical/administrative functions but cannot perform activities requiring registration."),("Supervision","Registered principals supervise activities of representatives under firm supervisory systems.")]},
18:{"title":"Employee Conduct & Reportable Events","section":"Regulatory Framework","cards":[
("Form U5","Uniform termination notice filed when a registered person's association with a firm ends."),("Form U6","Regulator-filed form reporting certain disciplinary actions and events."),("BrokerCheck","FINRA public database providing registration and disclosure information about firms and securities professionals."),("Customer Complaint","Written complaint alleging grievance involving activities of an associated person or firm; triggers recordkeeping/reporting duties."),("Outside Business Activity","Compensated business activity outside scope of relationship with member firm, generally requiring prior written notice."),("Private Securities Transaction","Securities transaction outside regular scope of employment; may require notice and approval, especially if compensation is involved."),("Selling Away","Participation in private securities transactions without required firm approval."),("Gift Limit","FINRA non-cash gift rule generally limits gifts to $100 per person per year when related to the recipient's employer's business."),("Entertainment","Reasonable business entertainment may be treated differently from gifts when host attends and it is not excessive."),("Training/Education Exception","Offeror-paid education meetings may be permitted if conditions are met, including firm permission and appropriate location."),("Statutory Disclosures","Certain criminal, regulatory, civil, financial and customer events must be disclosed on registration forms."),("U4 Update","Registered persons and firms must keep Form U4 information current and amend reportable events within required timeframes."),("Political Contributions / G-37","MSRB pay-to-play rule can restrict municipal securities business after certain political contributions."),("Complaint Records","Firms must maintain records of written customer complaints and may have reporting obligations."),("Arbitration Disclosure","Form U4 includes agreement to arbitrate certain disputes under industry rules.")]},
19:{"title":"Economic Factors","section":"Capital Markets","cards":[
("GDP","Market value of goods and services produced within a country's borders."),("GNP","Production associated with a country's nationals, including certain activity abroad."),("Inflation","General increase in prices and decline in purchasing power."),("Deflation","General decrease in price levels."),("CPI","Widely followed measure of changes in consumer prices."),("Real Interest Rate","Nominal interest rate minus inflation rate, approximately."),("Expansion","Business-cycle phase of rising output and employment."),("Peak","High point before economic contraction."),("Contraction / Recession","Period of declining economic activity."),("Trough","Low point before recovery/expansion."),("Leading Indicator","Economic measure that tends to change before the overall economy."),("Lagging Indicator","Measure that tends to change after the economy has already shifted."),("Open Market Operations","Federal Reserve buying and selling government securities; frequently used monetary-policy tool."),("Discount Rate","Rate charged by Federal Reserve Banks on eligible loans to depository institutions."),("Normal Yield Curve","Upward-sloping curve in which longer maturities yield more than shorter maturities; often associated with expansion expectations."),("Inverted Yield Curve","Downward-sloping curve in which short rates exceed long rates; often viewed as a recession warning."),("Balance Sheet","Statement of assets, liabilities and shareholders' equity at a point in time."),("Income Statement","Statement of revenues and expenses over a period.")]},
20:{"title":"Investment Risks","section":"Products & Risks","cards":[
("Systematic Risk","Broad market risk that generally cannot be diversified away."),("Unsystematic Risk","Issuer- or investment-specific risk that diversification can reduce."),("Market Risk","Risk that overall market movements reduce an investment's value."),("Interest-Rate Risk","Risk that changes in rates affect fixed-income prices."),("Inflation Risk","Risk that purchasing power falls because prices rise."),("Business Risk","Risk arising from an issuer's operations, industry or competitive position."),("Liquidity Risk","Risk that an asset cannot be sold quickly at a fair price."),("Currency Risk","Risk that exchange-rate movements affect investment value."),("Political Risk","Risk that political events or policies adversely affect investments."),("Credit Risk","Risk that an issuer cannot meet debt obligations."),("Prepayment Risk","Risk that principal is returned earlier than expected, often forcing reinvestment at lower rates."),("Beta","Measure of a security's volatility relative to the overall market; commonly associated with systematic risk."),("Alpha","Return above or below a benchmark after considering risk assumptions."),("Duration","Measure of a bond's sensitivity to changes in interest rates."),("Strategic Asset Allocation","Long-term target allocation among asset classes."),("Tactical Asset Allocation","Shorter-term deviations from strategic targets based on market views."),("Passive Strategies","Examples include buy-and-hold, periodic rebalancing and indexing."),("Sector Rotation","Active strategy shifting exposure among sectors based on economic/market expectations.")]}
}

BLOCKS = {
1:[1,2,3,4,5],
2:[6,7,8,9,10],
3:[11,12,13,14,15],
4:[16,17,18,19,20],
}

SECTION_CHAPTERS = {
"Capital Markets":[1,2,11,19],
"Products & Risks":[3,4,5,7,8,9,10,20],
"Trading, Accounts & Prohibited Activities":[6,12,13,14,15,16],
"Regulatory Framework":[17,18],
}

SECTION_WEIGHTS = {
"Capital Markets":12,
"Products & Risks":33,
"Trading, Accounts & Prohibited Activities":23,
"Regulatory Framework":7,
}
