"""High-yield SIE math/formula deck aligned to concepts in the study curriculum."""

MATH_CARDS = [
("Current Yield", "Annual bond interest ÷ current market price. Example: $60 annual interest ÷ $960 price = 6.25%."),
("Annual Bond Interest", "Coupon rate × par value. Example: 6% × $1,000 = $60 per year."),
("Basis Points", "1 basis point = 0.01%; 100 basis points = 1%. A move from 4.25% to 4.75% is 50 basis points."),
("Bond Price / Yield Rule", "Interest rates or yields UP → existing bond prices DOWN. Rates or yields DOWN → bond prices UP."),
("Premium Bond Yield Order", "For a callable premium bond, typically Coupon/Nominal Yield > Current Yield > YTM > YTC when called at the relevant call terms."),
("Discount Bond Yield Order", "For a discount bond, typically Coupon/Nominal Yield < Current Yield < YTM. YTC depends on the call price and timing."),
("Yield to Maturity (YTM)", "Total annualized return if the bond is held to maturity, assuming promised payments are made and reinvestment assumptions hold. On SIE questions, know the relationship to coupon/current yield and premium/discount; exact calculator-style YTM computation is generally not the emphasis."),
("Yield to Call (YTC)", "Annualized return assuming a callable bond is redeemed on a specified call date at the call price. Know that an early call can reduce the return on a premium bond; exact iterative calculation is generally not the SIE emphasis."),
("Approximate YTM", "Approximation: [annual interest + (par − market price) ÷ years to maturity] ÷ [(par + market price) ÷ 2]. Use as a study aid for the relationship, not as a claim that FINRA requires calculator-level YTM solving."),
("Approximate YTC", "Approximation: [annual interest + (call price − market price) ÷ years to call] ÷ [(call price + market price) ÷ 2]. Use to understand call-return relationships."),
("Conversion Ratio", "Bond par value ÷ conversion price. Example: $1,000 ÷ $40 = 25 shares."),
("Conversion Parity Price", "Bond market price ÷ conversion ratio gives the common-stock parity price."),
("Current Market Value After Stock Split", "Shares × price. A proportional stock split changes shares and price but initially leaves total market value unchanged."),
("Forward Split", "Multiply shares by the split ratio and divide price proportionally. Example: 2-for-1: 100 shares at $60 → 200 shares at about $30."),
("Reverse Split", "Reduce shares and increase price proportionally. Example: 1-for-4: 400 shares at $5 → 100 shares at about $20."),
("Capital Gain / Loss", "Sales proceeds − adjusted cost basis. Positive = capital gain; negative = capital loss."),
("Total Return", "Investment income + change in value, divided by the original investment, for the measurement period."),
("NAV", "Investment-company assets − liabilities, divided by shares outstanding."),
("Mutual Fund POP", "For a front-end load fund: NAV ÷ (100% − sales-charge percentage)."),
("Sales Charge %", "(POP − NAV) ÷ POP × 100."),
("Long Call Breakeven", "Strike price + premium paid."),
("Long Put Breakeven", "Strike price − premium paid."),
("Call Intrinsic Value", "Market price − strike price, but never less than zero."),
("Put Intrinsic Value", "Strike price − market price, but never less than zero."),
("Option Time Value", "Option premium − intrinsic value."),
("Option Contract Multiplier", "Standard listed equity option generally represents 100 shares. Premium quote × 100 = contract premium dollars."),
("Long Option Maximum Loss", "Premium paid. Example: premium of 4.50 × 100 = $450 maximum loss for the buyer."),
("Long Call Maximum Gain", "Theoretically unlimited as the stock price rises."),
("Long Put Maximum Gain", "Strike price − premium, multiplied by 100, if the stock falls to zero."),
("Uncovered Call Maximum Loss", "Theoretically unlimited because the stock price can rise without a fixed ceiling."),
("Real Interest Rate", "Approximately nominal interest rate − inflation rate. Example: 6% nominal − 2% inflation = about 4% real."),
("Market Capitalization", "Shares outstanding × current market price per share."),
("Balance Sheet Equation", "Assets = Liabilities + Shareholders' Equity."),
("SIPC Numbers", "$500,000 maximum protection per separate customer, including up to $250,000 for cash; this is a limit to memorize, not a calculation of market-loss protection."),
("CTR Threshold", "Qualifying cash transactions exceeding $10,000 trigger CTR requirements; memorize the threshold."),
]
