"""Premium, original SIE application items for the highest-weight content areas.
These are NOT copied from FINRA or any commercial prep provider. They are built from the
uploaded STC curriculum plus the public FINRA outline, using close distractors and multi-step logic.
Each tuple: stem, choices, correct answer, explanation, term, difficulty.
"""
import random

PREMIUM = {
3:[
("A corporation has 20 million authorized common shares, has issued 12 million, and currently holds 2 million shares in treasury. It announces a cash dividend payable to holders of outstanding common stock. On how many shares will the dividend generally be paid?",["8 million","10 million","12 million","20 million"],"10 million","Outstanding shares equal issued shares minus treasury shares. Authorized shares are only the charter ceiling; treasury shares are not outstanding and generally do not receive dividends.","Outstanding Shares",3),
("An investor wants current dividend priority over common stock but also wants the possibility of participating in future common-stock appreciation through an exchange feature. Which security MOST directly combines those objectives?",["cumulative preferred stock","convertible preferred stock","treasury stock","a common-stock warrant only"],"convertible preferred stock","Preferred stock provides dividend priority over common; a conversion feature provides a path into common equity. Cumulative preferred addresses missed dividends, not conversion into common.","Convertible Preferred",3),
("A shareholder owns 5% of a corporation and is concerned that a new common-stock offering could reduce that percentage. Which corporate right, if available, MOST directly addresses this concern?",["preemptive right","cumulative dividend provision","call protection","conversion privilege on a bond"],"preemptive right","Preemptive rights may allow an existing common shareholder to buy a proportional amount of a new issue to maintain percentage ownership.","Preemptive Right",2)],
4:[
("Two otherwise similar 6% bonds mature in 3 years and 25 years. Market rates rise by 100 basis points. Which statement is MOST accurate?",["The 3-year bond should fall more because it matures sooner","The 25-year bond should generally fall more because its fixed cash flows extend farther into the future","Both bonds must fall by exactly 1%","Neither bond should move because their coupon rates are unchanged"],"The 25-year bond should generally fall more because its fixed cash flows extend farther into the future","Bond prices move inversely to rates, and longer maturities generally have greater interest-rate sensitivity. Coupon dollars stay fixed; market price adjusts.","Interest-Rate Risk",3),
("An investor pays 108 for a callable bond with a 7% coupon. Comparable market yields later fall substantially and the issuer calls the bond at 102. Which combination BEST describes the investor's principal concerns?",["reinvestment risk and loss of part of the premium paid","credit risk and a guaranteed capital gain","inflation risk only and no call-related effect","preemptive-right risk and dilution"],"reinvestment risk and loss of part of the premium paid","A call after rates fall can force reinvestment at lower yields. A buyer who paid 108 and receives a 102 call price also does not recover the full premium paid.","Call Provision",3),
("A 5% $1,000 par bond is quoted at 92. Which statement is TRUE?",["The bond pays $46 annually and has a current yield below 5%","The bond pays $50 annually and has a current yield above 5%","The bond pays $50 annually and has a current yield exactly 5%","The coupon automatically rises because the bond trades at a discount"],"The bond pays $50 annually and has a current yield above 5%","Annual interest is 5% of $1,000, or $50. Current yield uses market price; paying $920 makes $50/$920 greater than 5%.","Current Yield",3),
("A $1,000 convertible bond has a conversion price of $50 and trades at $1,080. Ignoring accrued interest, at what common-stock price would the shares received on conversion have a market value equal to the bond's $1,080 market price?",["$50","$54","$56","$60"],"$54","Conversion ratio is $1,000/$50 = 20 shares. Parity stock price using the bond's market price is $1,080/20 = $54.","Conversion Ratio",3)],
5:[
("A high-income investor compares a 3.6% municipal bond with taxable corporate debt. If the investor's marginal tax rate is 28%, the municipal bond's approximate tax-equivalent yield is closest to:",["2.59%","3.60%","5.00%","6.48%"],"5.00%","Tax-equivalent yield = tax-exempt yield/(1-tax rate) = .036/.72 = .05, or 5.00%.","GO Municipal Bond",3),
("Interest rates decline rapidly. Which fixed-income investor is MOST exposed to receiving principal back sooner than expected precisely when reinvestment opportunities have become less attractive?",["an investor in mortgage-backed securities","an investor in a noncallable Treasury note","an investor in common stock","an investor in a zero-coupon corporate bond solely because it pays no current interest"],"an investor in mortgage-backed securities","Falling rates encourage mortgage refinancing, increasing prepayments and forcing investors to reinvest returned principal at lower rates.","Prepayment Risk",3),
("A county finances a public hospital with bonds payable solely from hospital revenues rather than from a pledge of the county's taxing power. Which analysis is MOST relevant to the bondholder?",["the project's ability to generate sufficient revenues","the county's unrestricted ad valorem taxing authority as the primary source of payment","the corporation's secured-debt covenant","whether the Treasury will guarantee the payments"],"the project's ability to generate sufficient revenues","A revenue bond depends primarily on revenues from the financed facility/project, so revenue sufficiency is central.","Revenue Bond",3),
("Which pairing is correctly matched?",["Treasury bill — long-term coupon security","commercial paper — short-term unsecured corporate debt","banker's acceptance — municipal debt backed by taxes","debenture — secured corporate debt backed by pledged collateral"],"commercial paper — short-term unsecured corporate debt","Commercial paper is unsecured short-term corporate borrowing. The other pairings reverse or misstate core characteristics.","Commercial Paper",2)],
7:[
("A customer has $92,000 already invested in eligible Class A shares of one fund family and wants to invest another $10,000. The next breakpoint is $100,000. Before recommending the purchase, which feature should the representative consider FIRST?",["rights of accumulation","a contingent deferred sales charge on Class C shares","forward pricing","the fund's portfolio turnover only"],"rights of accumulation","Rights of accumulation can combine existing eligible holdings with a new purchase to qualify for a breakpoint. The issue is sales-charge eligibility, not pricing time or portfolio turnover.","Rights of Accumulation",3),
("A representative recommends that a customer redeem one mutual fund and buy another very similar fund, creating a new sales charge, although the customer's objective and risk profile have not changed. Which concern is MOST directly raised?",["switching for unnecessary sales charges","a breakpoint sale only","forward-pricing violation automatically","dollar-cost averaging"],"switching for unnecessary sales charges","Moving between similar funds without a customer-driven reason can be an improper switching practice if it creates unnecessary costs.","Switching",3),
("A customer buys shares of a closed-end fund at $21 while its NAV is $19.50. Which statement is MOST accurate?",["The purchase violates forward pricing because the customer paid above NAV","The shares are trading at a premium to NAV in the secondary market","The fund must redeem the shares at $21","The customer has purchased Class A mutual fund shares with a front-end load"],"The shares are trading at a premium to NAV in the secondary market","Closed-end funds trade intraday in the secondary market, so market price can be above or below NAV.","Closed-End Fund",3),
("An open-end mutual fund has NAV of $18.40 and a public offering price of $20.00. The sales charge as a percentage of POP is:",["8.0%","8.7%","9.2%","10.0%"],"8.0%","Sales charge percentage = (POP-NAV)/POP = ($20.00-$18.40)/$20.00 = 8%.","POP",3)],
8:[
("A variable annuity owner is 15 years from retirement and asks why contract value can decline even though the product is issued by an insurance company. Which explanation is BEST?",["The separate account holds market-sensitive investments and the contract owner bears that investment risk","All insurance products are guaranteed only by SIPC","The general account passes all investment risk directly to the customer","The annuitant, rather than the owner, guarantees the investment return"],"The separate account holds market-sensitive investments and the contract owner bears that investment risk","Variable-annuity separate-account performance fluctuates with investments; the owner bears investment risk. Insurance-company guarantees do not turn the separate account into a fixed account.","Separate Account",3),
("A nonqualified variable annuity was purchased entirely with after-tax dollars. Which statement BEST describes the tax concept tested when distributions begin?",["The investment in the contract represents basis, while earnings have been tax-deferred","All distributions are tax-free because contributions were after-tax","The entire contract value is taxable each year during accumulation","The contract receives municipal-bond tax treatment"],"The investment in the contract represents basis, while earnings have been tax-deferred","After-tax contributions create basis; earnings generally grow tax-deferred. Tax deferral does not mean all future distributions are tax-free.","Nonqualified Annuity",3),
("An annuity contract is owned by Parent, measures benefits using Child's life, and names Spouse to receive the death benefit. Who is the annuitant?",["Parent","Child","Spouse","the insurance company"],"Child","The annuitant is the measuring life. The owner controls contract rights; the beneficiary receives the applicable death benefit.","Annuitant",2)],
9:[
("An investor wants exchange-traded exposure to a commodity index but is especially concerned about the issuer becoming insolvent even if the index performs well. Which product structure MOST directly creates that concern?",["ETN","ETF organized as a fund","equity REIT","open-end mutual fund"],"ETN","An ETN is unsecured debt of the issuer, so issuer credit risk is a defining concern even if the linked index performs well.","ETN",3),
("An investor buys a 2x leveraged ETF and expects to hold it for six months. Which statement is MOST important to understand?",["The fund's objective is generally tied to a multiple of DAILY performance, so compounding can cause long-term results to differ from 2x the index's cumulative return","The fund guarantees exactly twice the six-month return of the index","The fund eliminates market risk by using leverage","The ETF's issuer credit risk is identical to an unsecured ETN solely because both trade on an exchange"],"The fund's objective is generally tied to a multiple of DAILY performance, so compounding can cause long-term results to differ from 2x the index's cumulative return","Daily reset and compounding make long-horizon results path-dependent; a leveraged ETF is not a promise of the same multiple over arbitrary holding periods.","Leveraged ETF",3),
("A limited partner begins actively managing partnership operations and negotiating contracts on behalf of the partnership. Which concern is MOST relevant?",["The investor may jeopardize the passive limited-partner role associated with limited liability","The investor automatically becomes a bondholder","The partnership must convert to a mutual fund","The investor receives SIPC protection against partnership losses"],"The investor may jeopardize the passive limited-partner role associated with limited liability","Limited partners are generally passive investors. Active management is associated with the general partner role and can undermine the limited-liability distinction.","Limited Partner",3)],
10:[
("An investor owns 100 XYZ shares at $58 and buys one XYZ 55 put for a premium of 3. Which statement BEST describes the position at expiration?",["The put establishes a $55 sale right on the shares, with protection costing the $3 premium","The put obligates the investor to sell the shares at $55","The position is a covered call and caps upside at $55","The put guarantees the investor cannot lose any money below the purchase price of $58"],"The put establishes a $55 sale right on the shares, with protection costing the $3 premium","A long put gives the right to sell at the strike. Combined with long stock it is a protective put; the premium means the hedge has a cost and does not guarantee no loss relative to the original $58 purchase price.","Protective Put",3),
("XYZ stock is $47. An XYZ 50 put is quoted at 5. Which statement is MOST accurate?",["The put has $3 intrinsic value and $2 time value","The put has $5 intrinsic value and no time value","The put has no intrinsic value because market price is below strike","The put has $2 intrinsic value and $3 time value"],"The put has $3 intrinsic value and $2 time value","Put intrinsic value = strike - market = $3. Premium $5 minus intrinsic $3 leaves $2 time value.","Time Value",3),
("A customer writes an uncovered XYZ 40 call for a premium of 2. Which risk statement is MOST accurate?",["Maximum loss is limited to the $200 premium received","Loss can be theoretically unlimited as the stock rises","Maximum gain is unlimited while maximum loss is $4,000","The position is bullish because the customer receives premium"],"Loss can be theoretically unlimited as the stock rises","An uncovered call writer must deliver stock at the strike if assigned and does not own the shares; as market price rises, potential loss has no fixed ceiling.","Uncovered Call",3),
("An investor buys one 60 call for 4 and one 60 put for 4 on the same stock with the same expiration. Without naming the strategy, what market expectation BEST fits the position?",["A large move in either direction is desirable because both options are owned","A flat market is ideal because both premiums decay to zero","Only a moderate rise can produce profit","The investor has no time-value exposure"],"A large move in either direction is desirable because both options are owned","Owning both a call and put at the same strike requires enough movement in either direction to overcome total premiums. A flat market hurts both long options through time decay.","Option Buyer Max Loss",3)],
20:[
("A diversified equity portfolio falls sharply after a broad recession causes nearly every sector to decline. Which statement is MOST accurate?",["Diversification should have eliminated this loss","The loss illustrates systematic risk that diversification cannot fully remove","The loss is purely unsystematic because each company is different","The portfolio is experiencing only liquidity risk"],"The loss illustrates systematic risk that diversification cannot fully remove","Broad market/economic risk is systematic. Diversification can reduce issuer-specific risk but cannot eliminate market-wide exposure.","Systematic Risk",3),
("Two bonds have similar credit quality and maturity, but Bond A has materially higher duration. If interest rates rise by the same amount, which conclusion is MOST reasonable?",["Bond A should generally experience greater price sensitivity","Bond A must have lower credit risk","Bond A's coupon will automatically rise","Duration predicts issuer default rather than rate sensitivity"],"Bond A should generally experience greater price sensitivity","Duration is a measure of interest-rate sensitivity; higher duration generally implies a larger percentage price response to a given rate move.","Duration",3),
("A U.S. investor owns stock of a profitable foreign company. The company's local share price is unchanged, but its home currency falls sharply versus the dollar. Which risk can reduce the U.S. investor's dollar return?",["currency risk","prepayment risk","call risk","preemptive-right risk"],"currency risk","Exchange-rate movements can reduce the dollar value of a foreign investment even when the underlying local-market price is unchanged.","Currency Risk",3)],
6:[
("An investor buys a stock for $40, receives $1.20 in dividends, and sells the stock one year later for $43.80. Ignoring taxes and commissions, the one-year total return is:",["3.0%","7.5%","12.5%","15.0%"],"12.5%","Total return = ($1.20 income + $3.80 gain)/$40 = $5/$40 = 12.5%.","Total Return",3),
("A bond with a 6% coupon is priced at a premium. Which ordering is generally correct if the bond is held to maturity?",["coupon rate > current yield > YTM","YTM > current yield > coupon rate","current yield > coupon rate > YTM","all yields must be equal"],"coupon rate > current yield > YTM","On a premium bond, the investor pays more than par but receives only par at maturity, reducing YTM below current yield and coupon rate.","Premium Yield Relationship",3),
("A bond's yield moves from 5.20% to 4.85%. The change is:",["a decrease of 3.5 basis points","a decrease of 35 basis points","an increase of 35 basis points","a decrease of 350 basis points"],"a decrease of 35 basis points","The difference is 0.35 percentage point, which equals 35 basis points.","Basis Point",3)],
12:[
("ABC trades at 48. A customer wants to buy only if the stock shows upward momentum and reaches 52, then wants immediate execution. Which order BEST matches the instruction?",["buy stop at 52","buy limit at 52","sell stop at 52","sell limit at 52"],"buy stop at 52","A buy stop is placed above the current market and, when triggered, becomes a market order. A buy limit would seek 52 or lower and could execute immediately near 48.","Buy Stop",3),
("A customer owns XYZ at 72 and wants downside protection, but refuses to sell below 67 once the protective trigger at 68 is reached. Which order BEST expresses that trade-off?",["sell stop-limit with stop 68 and limit 67","sell stop at 68","sell limit at 68","buy stop-limit with stop 68 and limit 67"],"sell stop-limit with stop 68 and limit 67","A stop-limit can trigger at 68 and then become a sell limit at 67, providing price protection but creating the risk of no execution if the market gaps below 67.","Stop-Limit Order",3),
("A customer instructs an RR to buy 500 shares of a named stock but tells the RR to choose the best time and price during the day. Which statement is MOST accurate?",["This is limited time-and-price discretion on a specified order, not full discretionary authority over the account","The RR now has authority to choose any security and amount","The instruction is prohibited unless the account is a margin account","The order must be treated as a market order immediately"],"This is limited time-and-price discretion on a specified order, not full discretionary authority over the account","Time/price discretion on a specified order differs from broad discretion over security, action and amount.","Not-Held Order",3),
("A customer enters a market order during a period of extreme volatility. Which risk is MOST directly associated with that order choice?",["The execution price can differ materially from the last quoted price","The order might never execute because a market order prioritizes price","The order guarantees a maximum purchase price","The order automatically becomes a stop-limit order"],"The execution price can differ materially from the last quoted price","Market orders prioritize execution, not a specific price. In volatile or thin markets, slippage can be significant.","Market Order",3)],
13:[
("A customer owns 300 shares at $24 immediately before a 3-for-2 stock split. Ignoring market movement, which post-split position is approximately equivalent?",["200 shares at $36","450 shares at $16","600 shares at $12","450 shares at $24"],"450 shares at $16","A 3-for-2 split multiplies shares by 1.5 and divides price by 1.5, preserving the initial $7,200 market value.","Forward Split",3),
("A shareholder sells stock after the record date but before receiving a distribution that economically belongs to the buyer under applicable market rules. Which mechanism can transfer the distribution to the entitled buyer?",["due bill","proxy","stock power","red herring"],"due bill","A due bill can transfer a distribution when record-date mechanics and economic entitlement differ.","Due Bill",3),
("A stock trade occurs on Thursday and Friday is a normal business day. Under regular-way T+1 settlement, when should it normally settle?",["Thursday","Friday","the following Monday","two business days later"],"Friday","T+1 means one business day after the trade date when there is no intervening market holiday.","Regular-Way Equity Settlement",2)],
14:[
("A client dies while holding a JTWROS account with one surviving joint tenant. Which result is MOST consistent with the account registration?",["The deceased owner's interest generally passes to the surviving joint tenant","The deceased owner's share automatically passes through the probate estate as in tenants in common","The broker-dealer becomes the owner until probate is complete","The account converts into a UGMA account"],"The deceased owner's interest generally passes to the surviving joint tenant","Rights of survivorship distinguish JTWROS from tenants in common.","Joint Tenants with Rights of Survivorship",3),
("An RR has written authority to choose securities and amounts in a customer's account. Which control is MOST directly required in addition to customer authorization?",["firm approval and supervision of the discretionary account","SIPC approval of each trade","FDIC insurance on the securities","municipal issuer approval"],"firm approval and supervision of the discretionary account","Full discretion requires appropriate customer authorization and firm approval/supervision; SIPC and FDIC do not approve trades.","Discretionary Account",3),
("A customer wants an account for a minor, but wants the contribution to remain revocable so the donor can take it back at any time. Why is a standard UGMA/UTMA account a poor fit?",["A completed custodial gift is generally irrevocable","UGMA/UTMA accounts allow only corporate bonds","The minor must be over age 18 when the account is opened","The custodian becomes the beneficial owner"],"A completed custodial gift is generally irrevocable","Assets transferred to a UGMA/UTMA account are an irrevocable gift to the minor; the custodian manages rather than beneficially owns them.","UGMA/UTMA",3)],
15:[
("A customer deposits $9,800 in cash on Monday and $9,700 in cash on Tuesday after asking what amount would avoid a report. Which issue is MOST important even though neither deposit individually exceeds $10,000?",["possible structuring and suspicious activity requiring AML review","no AML concern because each transaction is below $10,000","automatic SIPC liquidation","a mutual-fund breakpoint sale"],"possible structuring and suspicious activity requiring AML review","Breaking transactions into smaller amounts to evade reporting can be structuring and may warrant suspicious-activity reporting. The analysis is not limited to a single transaction crossing the CTR threshold.","SAR",3),
("A retail customer has a long time horizon, moderate risk tolerance, and a need for emergency liquidity. An RR recommends placing nearly all liquid net worth into an illiquid alternative investment because it pays a high commission. Which obligation is MOST directly implicated?",["the duty to act in the retail customer's best interest and not place the representative's interest ahead","CIP identity verification only","CTR cash reporting only","proxy-voting rules only"],"the duty to act in the retail customer's best interest and not place the representative's interest ahead","The recommendation conflicts with liquidity needs and appears driven by compensation. The recommendation standard, not identity or cash reporting, is central.","Regulation Best Interest",3),
("A firm sends the same promotional email to 40 retail customers during a 30-day period. How is the communication generally classified in the curriculum?",["retail communication","correspondence","institutional communication","internal communication"],"retail communication","Distribution to more than 25 retail investors within 30 calendar days is generally a retail communication.","Retail Communication",2),
("Which sequence correctly describes the classic stages of money laundering?",["placement, layering, integration","layering, placement, integration","integration, placement, layering","placement, integration, layering"],"placement, layering, integration","Placement introduces illicit funds; layering obscures their source; integration returns funds appearing legitimate.","Layering",2)],
16:[
("An RR places a low-activity customer into a fee-based account and leaves the account largely untouched for years while ongoing fees accumulate. Which concern is MOST directly raised?",["reverse churning","front-running","marking the close","freeriding"],"reverse churning","Reverse churning can arise when a fee-based arrangement is inappropriate for an inactive account because ongoing fees are not justified by services/activity.","Reverse Churning",3),
("A trader buys shares minutes before publishing a favorable research report that the trader knows is likely to move the stock. Which concern is MOST directly raised?",["trading ahead of research","freeriding","interpositioning","breakpoint selling"],"trading ahead of research","Using knowledge of an imminent research report to trade first raises trading-ahead concerns distinct from customer-order front-running.","Trading Ahead of Research",3),
("A broker routes a customer order through an unnecessary third party that adds cost but provides no meaningful execution benefit. This practice is MOST closely associated with:",["interpositioning","front-running","layering","dollar-cost averaging"],"interpositioning","Interpositioning inserts an unnecessary party between the customer and market and can conflict with best execution.","Interpositioning",3),
("A customer tells an RR that losses would be financially devastating. The RR responds, 'Don't worry—if this stock falls, I will personally reimburse you.' Which statement is MOST accurate?",["The promise is improper because an RR may not guarantee a customer against securities loss","The promise is permitted if made orally rather than in writing","The promise is permitted for investment-grade securities","The promise is required under Reg BI"],"The promise is improper because an RR may not guarantee a customer against securities loss","Customer consent or good intentions do not make a guarantee against investment loss permissible.","Guarantee Against Loss",2)]
}

def premium_for_chapter(ch):
    out=[]
    for stem,choices,answer,why,term,difficulty in PREMIUM.get(ch,[]):
        c=list(choices);random.shuffle(c)
        out.append({"q":stem,"c":c,"a":answer,"why":why,"chapter":ch,"term":term,"style":"application","difficulty":difficulty,"premium":True})
    return out
