"""Original application-heavy SIE scenario bank.
Grounded in the user's 20-chapter STC manual. Uses FINRA-style item logic (closed stem,
BEST/MOST, EXCEPT, scenario/application, calculations) without copying FINRA questions.
"""
import random

SCENARIOS = {
1:[
("A broker-dealer buys 5,000 shares from a customer into the firm's inventory and later resells them. In the first transaction, the firm is acting primarily as a:",["broker because it matched two customers","dealer because it traded for its own account","transfer agent because ownership changed","clearing firm because settlement will occur"],"dealer because it traded for its own account","The defining issue is capacity: trading for the firm's own account is dealer/principal activity.","Dealer"),
("A corporation sells newly issued shares to investors and receives the proceeds. Which statement is MOST accurate?",["The transaction is in the secondary market because investors are involved","The transaction is in the primary market because the issuer receives capital","The transaction is in the fourth market because no exchange is required","The transaction is a dealer trade because the issuer is selling securities"],"The transaction is in the primary market because the issuer receives capital","Primary market means the issuer is selling new securities and receives the proceeds.","Primary Market"),
("An institution wants to trade a large block anonymously with minimal displayed market impact. Which venue is MOST consistent with that objective?",["dark pool","primary market syndicate","transfer agent window","municipal underwriting desk"],"dark pool","Dark pools conceal displayed quotations and are used by large participants seeking lower market impact.","Dark Pools"),
("Two large institutions arrange a direct trade with one another outside the public exchange market. This is MOST closely associated with the:",["primary market","third market","fourth market","auction market only"],"fourth market","Fourth-market activity is direct institution-to-institution trading.","Fourth Market"),
("After a trade is executed, the parties' obligations are compared and prepared for completion before payment and delivery occur. This stage is BEST described as:",["underwriting","clearing","distribution","registration"],"clearing","Clearing confirms/processes trade obligations; settlement completes payment and delivery.","DTCC"),
("A small broker-dealer solicits customers and accepts orders but relies on another broker-dealer for custody, clearing and settlement. The small firm is MOST likely a(n):",["introducing firm","transfer agent","market maker in every transaction","issuer"],"introducing firm","An introducing firm can handle customer relationships while a carrying/clearing firm performs back-office functions.","Introducing Firm")],
2:[
("An issuer is preparing to sell a new public offering. Which federal law is MOST directly associated with registration and disclosure of that new issue?",["Securities Act of 1933","Securities Exchange Act of 1934","Investment Advisers Act of 1940","SIPA of 1970"],"Securities Act of 1933","The 1933 Act focuses on new issues and primary-market disclosure.","Securities Act of 1933"),
("A question concerns regulation of secondary-market trading and the federal agency created to administer federal securities laws. Which pairing is BEST?",["1933 Act and FDIC","1934 Act and SEC","1940 Company Act and MSRB","SIPA and NASAA"],"1934 Act and SEC","The 1934 Act created the SEC and is central to secondary-market regulation.","Securities Exchange Act of 1934"),
("A customer loses money because a stock price falls after purchase. Which statement about SIPC is MOST accurate?",["SIPC reimburses the market loss up to its coverage limit","SIPC may protect qualifying customer assets if a member broker-dealer fails, but not market losses","SIPC guarantees bond principal but not stock principal","SIPC applies only to bank deposits"],"SIPC may protect qualifying customer assets if a member broker-dealer fails, but not market losses","SIPC is not market-loss insurance; it addresses customer assets in a failed member broker-dealer.","SIPA / SIPC"),
("Which organization writes rules for municipal securities dealers and municipal advisors but generally relies on other regulators for enforcement?",["SEC","FINRA","MSRB","FDIC"],"MSRB","MSRB is the municipal rulemaking body; enforcement is performed by FINRA, SEC and banking regulators as applicable.","MSRB"),
("A broker-dealer needs firm-specific policies assigning supervisory responsibility and procedures for complying with securities rules. The firm should look primarily to its:",["WSP manual","prospectus","Form U5","corporate charter"],"WSP manual","Written supervisory procedures document the firm's supervisory system and responsibilities.","Written Supervisory Procedures"),
("A dispute seeks monetary damages between a customer and a broker-dealer. Which FINRA process is MOST directly designed to resolve that dispute?",["Code of Arbitration","Code of Procedure","SIPC liquidation","SEC registration review"],"Code of Arbitration","Arbitration resolves monetary disputes; the Code of Procedure addresses disciplinary matters.","Code of Arbitration")],
3:[
("A company has issued 10 million shares and later repurchases 2 million shares. Ignoring any other changes, how many shares are outstanding?",["8 million","10 million","12 million","2 million"],"8 million","Outstanding shares equal issued shares minus treasury shares.","Outstanding Shares"),
("An investor wants dividend priority over common shareholders but is willing to give up much of common stock's voting profile. Which security BEST fits?",["common stock","preferred stock","warrant","Treasury stock"],"preferred stock","Preferred stock generally has dividend/liquidation preference over common equity.","Preferred Stock"),
("A corporation missed preferred dividends last year. Before it can resume common dividends, those missed preferred dividends must be paid. The preferred stock is MOST likely:",["convertible","cumulative","participating only","treasury"],"cumulative","Cumulative preferred carries unpaid dividends forward as arrears.","Cumulative Preferred"),
("A shareholder wants to preserve the same ownership percentage when the corporation issues additional common shares. Which right is MOST relevant?",["preemptive right","conversion privilege","call protection","put provision"],"preemptive right","Preemptive rights may allow existing common shareholders to maintain proportional ownership.","Preemptive Right"),
("Which statement about treasury stock is MOST accurate?",["It is authorized but never issued","It is issued stock repurchased by the corporation and generally has no vote or dividend while held","It is preferred stock held by a trustee","It is outstanding stock held by retail customers"],"It is issued stock repurchased by the corporation and generally has no vote or dividend while held","Treasury shares are issued but not outstanding while held by the issuer.","Treasury Stock"),
("A U.S. investor buys a receipt trading in U.S. markets that represents shares of a foreign company. The investor owns a(n):",["ADR","municipal note","REIT","warrant only"],"ADR","An ADR represents an interest in shares of a foreign issuer and trades in U.S. markets.","ADR")],
4:[
("A 6% $1,000 par bond is trading at $900. Which statement is MOST accurate?",["Its coupon rate has risen above 6%","Its annual coupon remains $60 and its current yield is above 6%","Its annual coupon falls because market price fell","Its current yield must equal 6%"],"Its annual coupon remains $60 and its current yield is above 6%","Coupon dollars are based on par; paying less than par raises current yield above the coupon rate.","Current Yield"),
("Market interest rates rise sharply. All else equal, which bond is generally expected to experience the GREATER percentage price decline?",["a longer-maturity fixed-rate bond","a shorter-maturity fixed-rate bond","a matured bond","cash"],"a longer-maturity fixed-rate bond","Longer maturities generally have greater interest-rate sensitivity.","Interest-Rate Risk"),
("A callable premium bond is redeemed earlier than the investor expected after market rates fall. Which risk is MOST directly illustrated?",["reinvestment risk","voting risk","preemptive-right risk","currency risk only"],"reinvestment risk","The investor receives principal back and may have to reinvest at lower prevailing yields.","Call Provision"),
("An investor owns a convertible bond with a $1,000 par value and a $40 conversion price. What is the conversion ratio?",["20 shares","25 shares","40 shares","100 shares"],"25 shares","Conversion ratio = par value divided by conversion price = 1,000/40 = 25.","Conversion Ratio"),
("Which statement BEST explains why an existing bond's price usually falls when newly issued comparable bonds offer higher coupons?",["The old bond's fixed cash flows become less competitive","The old bond automatically changes its coupon","The issuer must immediately call the old bond","The bond's par value declines"],"The old bond's fixed cash flows become less competitive","Market price adjusts so the old fixed cash flows offer a competitive return.","Price-Yield Relationship"),
("A corporate bond is not secured by specific collateral. The investor is relying primarily on the issuer's overall ability to repay. The bond is a:",["debenture","mortgage bond","revenue bond","secured note"],"debenture","A debenture is unsecured corporate debt backed by general credit.","Credit Risk")],
5:[
("A city issues bonds to build a toll road, with debt service expected primarily from toll collections. The bonds are MOST likely:",["GO bonds","revenue bonds","Treasury notes","debentures"],"revenue bonds","Revenue bonds are supported primarily by project/facility revenues.","Revenue Bond"),
("A municipality issues debt supported primarily by its taxing authority. Which security is MOST likely?",["GO municipal bond","revenue bond","commercial paper","banker's acceptance"],"GO municipal bond","GO bonds rely primarily on the issuer's taxing power.","GO Municipal Bond"),
("Mortgage rates fall and homeowners refinance rapidly. An investor in mortgage-backed securities is MOST concerned that:",["principal will be returned sooner and reinvested at lower rates","the coupon rate will automatically increase","municipal taxes will fall","the security becomes common stock"],"principal will be returned sooner and reinvested at lower rates","Falling rates can accelerate prepayments, returning principal early.","Prepayment Risk"),
("Which Treasury security is typically issued with an original maturity of one year or less and sold at a discount?",["Treasury bill","Treasury note","Treasury bond","TIPS only"],"Treasury bill","T-bills are short-term discount obligations.","Treasury Bill"),
("A corporation needs unsecured short-term financing for working capital. Which instrument is MOST likely?",["commercial paper","mortgage bond","preferred stock","GO bond"],"commercial paper","Commercial paper is unsecured short-term corporate debt.","Commercial Paper"),
("Which mortgage-related issuer's securities carry explicit U.S. government backing as described in the manual?",["GNMA","FNMA","FHLMC","every mortgage REIT"],"GNMA","GNMA mortgage-backed securities carry explicit U.S. government backing; GSE status is not the same thing.","GNMA")],
6:[
("A $1,000 par bond pays a 7% annual coupon and is trading at $875. What is its current yield, approximately?",["7.00%","8.00%","8.75%","12.50%"],"8.00%","Annual interest is $70; $70/$875 = 8%.","Current Yield Formula"),
("Which yield relationship is generally correct for a bond purchased at a discount and held to maturity?",["coupon > current yield > YTM","coupon < current yield < YTM","YTM < coupon < current yield","all three must be equal"],"coupon < current yield < YTM","The discount creates an additional gain as price moves toward par at maturity.","Discount Yield Relationship"),
("A bond is purchased at a premium. Which factor causes YTM to be lower than the coupon rate, all else equal?",["the investor receives less than the purchase price back as par at maturity","the coupon automatically decreases","par value increases at maturity","the investor receives no interest"],"the investor receives less than the purchase price back as par at maturity","The premium paid is partly lost when only par is repaid at maturity.","Premium Yield Relationship"),
("An investor buys stock for $25, receives $1 in dividends, and the stock is worth $23 one year later. Which statement BEST describes total return?",["It considers only the $1 dividend","It considers the dividend and the $2 decline in value","It equals current yield on a bond","It ignores changes in market value"],"It considers the dividend and the $2 decline in value","Total return combines income and appreciation/depreciation relative to investment.","Total Return"),
("Bond A yields 4.55% and Bond B yields 4.95%. The difference is:",["4 basis points","40 basis points","400 basis points","0.04 basis points"],"40 basis points","0.40% equals 40 basis points.","Basis Point"),
("A candidate is asked to compute exact YTM using an iterative present-value calculation. According to the manual's emphasis, which response is MOST appropriate for SIE preparation?",["Exact YTM calculation is a core required calculation","Understand the concept and yield relationships; exact complex YTM calculation is not required","Ignore YTM entirely","Memorize only coupon rate"],"Understand the concept and yield relationships; exact complex YTM calculation is not required","The manual explicitly states exact YTM calculation is not required for exam purposes; conceptual understanding is.","Yield to Maturity")],
7:[
("A customer places an order to buy an open-end mutual fund at 11:00 a.m. Which price convention generally applies?",["the previous day's NAV","the next calculated NAV after receipt in good order","the intraday exchange bid","a negotiated dealer price"],"the next calculated NAV after receipt in good order","Open-end funds use forward pricing.","Forward Pricing"),
("A customer owns enough eligible Class A shares that an additional purchase would qualify for a reduced sales charge. Which feature is MOST relevant?",["breakpoint","12b-1 fee","CDSC only","short-sale rule"],"breakpoint","Breakpoints reduce front-end sales charges at specified investment levels.","Breakpoint"),
("A representative recommends that a customer invest just below a mutual-fund breakpoint, causing a higher sales charge. This is MOST likely:",["a breakpoint sale concern","dollar-cost averaging","forward pricing","rights of accumulation"],"a breakpoint sale concern","Recommending just below an available breakpoint can be an improper sales practice.","Breakpoint Sale"),
("Which product generally trades intraday between investors and may trade above or below NAV?",["closed-end fund","traditional open-end mutual fund","variable annuity accumulation unit only","bank CD"],"closed-end fund","Closed-end shares trade in the secondary market and market price can differ from NAV.","Closed-End Fund"),
("A customer wants to count existing eligible holdings toward a larger Class A purchase to qualify for a lower load. Which feature is MOST directly used?",["rights of accumulation","letter of intent only","12b-1 fee","forward pricing"],"rights of accumulation","ROA uses existing eligible holdings plus the new purchase for breakpoint eligibility.","Rights of Accumulation"),
("Which statement about dollar-cost averaging is MOST accurate?",["It guarantees profit if continued long enough","It invests equal dollar amounts periodically but cannot assure profit or prevent loss","It requires purchases only after market declines","It applies only to bonds"],"It invests equal dollar amounts periodically but cannot assure profit or prevent loss","The strategy disciplines periodic investing but does not eliminate market risk.","Dollar-Cost Averaging")],
8:[
("A variable annuity owner's separate-account investments decline. Who bears the investment risk?",["the contract owner","the insurer's general account","SIPC","the beneficiary only"],"the contract owner","Variable separate-account performance is borne by the contract owner.","Variable Annuity"),
("Which person controls the rights under an annuity contract, such as beneficiary designation and allocation choices, subject to contract terms?",["contract owner","annuitant only","beneficiary","transfer agent"],"contract owner","The owner controls contractual rights; the annuitant is the measuring life.","Contract Owner"),
("A client moves from accumulation units into a stream of annuity payments. The contract has entered the:",["annuity phase","cooling-off period","secondary market","underwriting period"],"annuity phase","Annuitization converts accumulated value into annuity payments.","Annuity Phase"),
("Which statement BEST distinguishes a fixed annuity from a variable annuity?",["The fixed annuity generally places investment risk on the insurer, while the variable annuity places market risk on the owner","Both always place investment risk entirely on the owner","Only variable annuities are insurance contracts","Fixed annuities use separate accounts exclusively"],"The fixed annuity generally places investment risk on the insurer, while the variable annuity places market risk on the owner","General-account guarantees support fixed contracts; variable values depend on separate-account performance.","Fixed Annuity"),
("A tax-deferred exchange is being considered from one qualifying annuity contract to another. Which provision is MOST relevant?",["Section 1035 exchange","Rule 144A","Regulation T","SIPC"],"Section 1035 exchange","A qualifying 1035 exchange can defer recognition of gain, subject to requirements.","1035 Exchange"),
("A state-sponsored account is being used for qualified education expenses. Which security/program is MOST likely involved?",["529 plan","LGIP for retail use","commercial paper","traditional IRA only"],"529 plan","529 plans are state-sponsored municipal fund securities designed for qualified education expenses.","529 Plan")],
9:[
("An investor buys an exchange-traded note linked to an index. Even if the index performs well, which additional risk is especially important?",["issuer credit risk","voting-right dilution","preemptive-right risk","municipal tax risk"],"issuer credit risk","An ETN is unsecured debt, so issuer creditworthiness matters.","ETN"),
("A leveraged ETF targets twice the DAILY return of an index. Which statement is MOST accurate for a long holding period?",["It must equal exactly twice the index's cumulative return","Compounding can cause the long-term result to differ materially from twice the cumulative index return","It has no market risk","Its return is guaranteed by the exchange"],"Compounding can cause the long-term result to differ materially from twice the cumulative index return","Leveraged ETF objectives are typically daily; path-dependent compounding matters over longer periods.","Leveraged ETF"),
("In a limited partnership, which participant generally manages the business and bears broader liability?",["general partner","limited partner","custodian","beneficiary"],"general partner","The GP manages; limited partners remain passive to preserve limited liability.","General Partner"),
("A REIT primarily owns and operates income-producing properties. It is MOST likely a(n):",["equity REIT","mortgage REIT","ETN","UIT"],"equity REIT","Equity REITs own/operate properties; mortgage REITs emphasize real-estate financing.","Equity REIT"),
("Which feature is MOST closely associated with many DPP limited-partnership structures?",["flow-through tax treatment","FDIC insurance","guaranteed liquidity","daily NAV redemption"],"flow-through tax treatment","Partnership results may pass through to partners.","Flow-Through Taxation"),
("An investor may need cash quickly. Which characteristic can make many alternative investments problematic?",["liquidity risk","preemptive rights","federal deposit insurance","automatic market making"],"liquidity risk","Many alternatives may be difficult to sell quickly at a fair price.","Liquidity Risk")],
10:[
("An investor owns stock and wants downside protection while retaining upside potential. Which strategy BEST fits?",["buy a protective put","write an uncovered call","sell the stock short against itself only","buy a put and sell the stock immediately"],"buy a protective put","Long stock plus long put establishes a floor-like downside hedge, subject to premium cost.","Protective Put"),
("A customer buys one XYZ 50 call for a premium of 4. What is the breakeven at expiration?",["46","50","54","58"],"54","Long call breakeven = strike + premium = 54.","Long Call Breakeven"),
("A customer buys one XYZ 50 put for a premium of 4. What is the breakeven at expiration?",["46","50","54","4"],"46","Long put breakeven = strike - premium = 46.","Long Put Breakeven"),
("A call has a strike of 40 and the stock is at 46. Ignoring time value, intrinsic value is:",["$0","$4","$6","$40"],"$6","Call intrinsic value = market price - strike when positive.","Intrinsic Value"),
("Which position has theoretically unlimited loss potential?",["long call","long put","uncovered short call","covered call"],"uncovered short call","A short uncovered call can lose without a fixed ceiling as the stock rises.","Uncovered Call"),
("A put buyer and a call writer are both generally positioned to benefit from which directional expectation?",["bearish","bullish","neutral only","rising interest rates only"],"bearish","Long puts and short calls are bearish positions.","Bearish Positions")],
11:[
("During the cooling-off period for a registered public offering, which action is generally permitted?",["accepting payment for the securities","completing final sales","providing a preliminary prospectus and recording nonbinding indications of interest","guaranteeing the final offering price"],"providing a preliminary prospectus and recording nonbinding indications of interest","The manual permits discussion/red herring distribution and nonbinding indications during cooling-off, but not final sales/payment.","Cooling-Off Period"),
("In a firm-commitment underwriting, who assumes the primary risk of reselling the securities to the public?",["the underwriter","the transfer agent","SIPC","the retail customer before purchase"],"the underwriter","The underwriter purchases the issue from the issuer and assumes distribution risk.","Firm Commitment"),
("Which document used during the cooling-off period typically omits the final offering price?",["red herring","statutory prospectus","Form U5","proxy"],"red herring","The preliminary prospectus does not include final pricing information.","Red Herring"),
("The SEC declares a registration statement effective. Which statement is MOST accurate?",["The SEC has approved the investment's merits","Sales may begin subject to offering requirements, but effectiveness is not a merit endorsement","The securities are guaranteed against loss","State laws no longer apply"],"Sales may begin subject to offering requirements, but effectiveness is not a merit endorsement","SEC effectiveness addresses registration/disclosure, not investment quality.","Registration Statement"),
("An underwriter agrees only to use its best efforts to sell an offering and does not purchase the entire issue for its own account. The arrangement is:",["best efforts","firm commitment","secondary distribution only","market making"],"best efforts","In best efforts the underwriter acts as agent rather than assuming full resale risk.","Best Efforts"),
("Rule 144A is MOST closely associated with resales of certain restricted securities to:",["QIBs","all retail customers","only municipalities","only bank depositors"],"QIBs","Rule 144A facilitates institutional resales to qualified institutional buyers.","Rule 144A")],
12:[
("A customer says, 'Buy the stock now; getting executed matters more to me than the exact price.' Which order is MOST appropriate?",["market order","buy limit","sell stop","stop-limit"],"market order","A market order prioritizes execution over price certainty.","Market Order"),
("A customer will buy ABC only at $40 or less. Which order BEST expresses that instruction?",["buy limit 40","buy stop 40","sell limit 40","market order"],"buy limit 40","A buy limit sets the maximum purchase price.","Buy Limit"),
("A customer owns a stock at $60 and wants an order that will trigger if the stock falls to $54, then seek immediate execution. Which order is MOST appropriate?",["sell stop 54","sell limit 54","buy stop 54","buy limit 54"],"sell stop 54","A sell stop below market can protect a long position; once triggered it becomes a market order.","Sell Stop"),
("A stop-limit order is triggered. What does it become?",["a market order","a limit order","a cancelled order","a GTC order automatically"],"a limit order","A stop-limit becomes a limit order after the trigger, so execution is not guaranteed.","Stop-Limit Order"),
("A firm acts as principal in a customer trade. Which compensation concept is MOST directly associated with this capacity?",["markup or markdown","commission only","advisory fee only","12b-1 fee only"],"markup or markdown","Dealer/principal trades generally involve markup/markdown rather than agency commission.","Principal Capacity"),
("Which statement about FINRA's 5% policy is MOST accurate?",["It is an absolute maximum commission in every transaction","It is a fairness guideline and the facts of the transaction matter","It applies only to mutual funds","It guarantees 5% compensation"],"It is a fairness guideline and the facts of the transaction matter","The 5% policy is not a fixed ceiling; reasonableness depends on circumstances.","5% Policy")],
13:[
("A customer buys stock on Monday in a regular-way transaction, with no market holiday. Under T+1, settlement is normally:",["Monday","Tuesday","Wednesday","Friday"],"Tuesday","T+1 means one business day after trade date.","Regular-Way Equity Settlement"),
("An investor owns 100 shares at $80 immediately before a 2-for-1 split. Ignoring market movement, the post-split position is approximately:",["50 shares at $160","100 shares at $40","200 shares at $40","200 shares at $80"],"200 shares at $40","A forward split doubles shares and halves price, leaving initial total market value unchanged.","Forward Split"),
("An investor owns 400 shares at $5 immediately before a 1-for-4 reverse split. Ignoring market movement, the new position is approximately:",["100 shares at $20","1,600 shares at $1.25","400 shares at $20","100 shares at $5"],"100 shares at $20","A 1-for-4 reverse split quarters shares and multiplies price by four.","Reverse Split"),
("A security is registered in the broker-dealer's name while the customer remains the beneficial owner. This is called:",["street name","book closure","firm commitment","proxy solicitation"],"street name","Street-name registration separates record holder from beneficial owner.","Street Name"),
("Which date determines that a buyer purchasing on or after that date generally does NOT receive the upcoming declared dividend?",["ex-date","record date","payable date","settlement date only"],"ex-date","The ex-dividend date determines entitlement for purchasers in the market.","Ex-Date"),
("A shareholder authorizes another party to vote shares on the shareholder's behalf. The authorization is a:",["proxy","stock power","due bill","prospectus"],"proxy","A proxy authorizes another party to vote shares.","Proxy")],
14:[
("A customer wants to purchase securities using funds borrowed from the broker-dealer. Which account is required?",["margin account","cash account","UGMA only","529 only"],"margin account","Margin accounts permit broker-dealer credit subject to applicable requirements.","Margin Account"),
("A customer authorizes an RR to decide the security, action and amount in the account. Which requirement is MOST directly implicated?",["discretionary-account authorization and firm approval","time-and-price discretion only","no approval because the customer gave oral consent","SIPC approval"],"discretionary-account authorization and firm approval","Full discretion over security/action/amount requires appropriate written authorization and firm approval.","Discretionary Account"),
("Two people want account ownership where a deceased owner's interest passes automatically to the surviving owner. Which registration is MOST appropriate?",["JTWROS","tenants in common","UGMA","individual account"],"JTWROS","JTWROS carries a survivorship feature.","Joint Tenants with Rights of Survivorship"),
("In a tenants-in-common account, what generally happens to a deceased owner's share?",["It passes through the deceased owner's estate","It automatically transfers to the surviving tenant","It is forfeited to the broker-dealer","It becomes Treasury stock"],"It passes through the deceased owner's estate","TIC ownership does not include automatic survivorship.","Tenants in Common"),
("A minor is the beneficial owner of assets managed by an adult custodian under a state custodial statute. The account is MOST likely:",["UGMA/UTMA","margin account","corporate account","joint account with survivorship"],"UGMA/UTMA","UGMA/UTMA accounts hold irrevocably gifted assets for a minor under a custodian.","UGMA/UTMA"),
("Which retirement-account statement is MOST accurate?",["Qualified Roth IRA distributions may be tax-free under applicable rules","Traditional IRA growth is taxed annually as earned","Original Roth IRA owners are always subject to the same RMD rules as traditional IRA owners","IRA securities are FDIC insured against market losses"],"Qualified Roth IRA distributions may be tax-free under applicable rules","Roth qualified distributions can be tax-free; traditional IRA earnings generally grow tax-deferred.","Roth IRA")],
15:[
("A new customer opens an account. The firm obtains identifying information and verifies identity. This process is MOST directly part of:",["CIP","CTR","SAR","proxy voting"],"CIP","The Customer Identification Program focuses on identity verification.","Customer Identification Program"),
("A customer makes a qualifying cash transaction exceeding $10,000. Which filing is MOST directly associated with the cash threshold?",["CTR","SAR automatically in every case","Form U4","proxy statement"],"CTR","CTR requirements generally apply to qualifying cash transactions over $10,000.","CTR"),
("A pattern of transactions appears structured and suspicious even though no single transaction alone explains the purpose. Which report is MOST directly associated with suspicious activity?",["SAR","CTR only","Form U5","SIPC claim"],"SAR","SARs report qualifying suspicious activity to FinCEN.","SAR"),
("A broker-dealer recommends a security to a retail customer. Which standard requires the recommendation to be in the customer's best interest without placing the firm's interest ahead?",["Regulation Best Interest","CIP","SIPC","Rule 144A"],"Regulation Best Interest","Reg BI governs recommendations to retail customers.","Regulation Best Interest"),
("Illicit money is moved through numerous transactions to obscure its origin. Which laundering stage is MOST directly illustrated?",["layering","placement","integration","settlement"],"layering","Layering obscures the source through multiple transactions.","Layering"),
("A communication is distributed to more than 25 retail investors within 30 calendar days. It is generally classified as:",["retail communication","correspondence","institutional communication","internal memo only"],"retail communication","The audience size threshold distinguishes retail communication from correspondence.","Retail Communication")],
16:[
("An RR repeatedly buys and sells securities in a customer's account primarily to generate commissions, inconsistent with the customer's objectives. This is MOST likely:",["churning","front-running","marking the close","freeriding"],"churning","Churning is excessive trading driven by compensation rather than customer needs.","Churning"),
("An RR learns that a customer is about to place a very large order and trades personally first to benefit from the expected market impact. This is MOST likely:",["front-running","reverse churning","interpositioning","dollar-cost averaging"],"front-running","Trading ahead of customer order flow is front-running.","Front-Running"),
("A person trades while possessing material nonpublic information in violation of applicable duties. This is MOST likely:",["insider trading","best execution","sector rotation","forward pricing"],"insider trading","MNPI plus improper trading is central to insider-trading violations.","Insider Trading"),
("A trader enters transactions near the close for the purpose of artificially influencing the closing price. This is MOST likely:",["marking the close","front-running","interpositioning","selling away"],"marking the close","The manipulative purpose of influencing the closing price is the key fact.","Marking the Close"),
("An RR tells a customer, 'I guarantee you cannot lose money on this stock.' The statement is:",["improper because securities losses may not be guaranteed by the representative","permitted for blue-chip stocks","permitted if the customer signs a waiver","required under Reg BI"],"improper because securities losses may not be guaranteed by the representative","Registered persons may not guarantee customers against investment loss.","Guarantee Against Loss"),
("A cash-account customer buys securities and sells them before paying for the purchase. This may create which violation?",["freeriding","front-running","layering","marking the close"],"freeriding","Freeriding generally involves selling a purchase before paying for it in a cash account.","Freeriding")],
17:[
("A person passes the SIE but has not yet associated with a member firm or passed the required representative-level qualification exam. Which statement is MOST accurate?",["The person may conduct all registered securities business immediately","Passing the SIE alone does not authorize registered securities activities","The person automatically becomes a principal","The person is exempt from registration for four years"],"Passing the SIE alone does not authorize registered securities activities","The SIE is a corequisite knowledge exam, not a standalone registration.","SIE"),
("Which form is used to apply for an associated person's securities registration and disclose required background information?",["Form U4","Form U5","Form U6","Form 10-K"],"Form U4","Form U4 is the individual registration and disclosure application.","Form U4"),
("A registered representative is unsure whether a proposed action violates a firm rule. Based on the manual's supervisory emphasis, the BEST next step is generally to:",["ask the designated supervisor/principal","guess based on customer preference","execute first and disclose later","contact SIPC"],"ask the designated supervisor/principal","The manual emphasizes designated supervision and notes escalation to the supervisor may be appropriate for rule clarification.","Supervision"),
("Which system maintains registration and disciplinary history for broker-dealers and registered persons?",["CRD","DTCC","OCC","EMMA"],"CRD","CRD is FINRA's registration database for firms and associated persons.","CRD"),
("Continuing education for registered persons includes which two broad elements?",["Regulatory Element and Firm Element","SIPC Element and SEC Element","Primary Element and Secondary Element","Retail Element and Institutional Element"],"Regulatory Element and Firm Element","FINRA CE includes Regulatory and Firm Elements.","Regulatory Element"),
("An unregistered employee is asked to perform an activity that requires securities registration. Which response is MOST appropriate?",["The employee should not perform the registered activity until properly registered","The employee may do it if supervised","The employee may do it once per month","The employee may do it for institutional customers only"],"The employee should not perform the registered activity until properly registered","Unregistered personnel are limited to functions that do not require registration.","Unregistered Personnel")],
18:[
("A registered person leaves a member firm. Which form is used to report the termination of association?",["Form U5","Form U4","Form U6","Form 8-K"],"Form U5","Form U5 is the uniform termination notice.","Form U5"),
("An RR participates in an outside securities transaction without required firm approval. This conduct is commonly referred to as:",["selling away","outside business activity only","churning","marking the close"],"selling away","Selling away is participation in private securities transactions without required firm approval.","Selling Away"),
("An RR starts a paid non-securities side business. Which concept is MOST directly implicated?",["outside business activity","private securities transaction automatically","front-running","new issue rule"],"outside business activity","A compensated business outside the member firm's scope generally triggers OBA notice requirements.","Outside Business Activity"),
("A written customer complaint alleges misconduct by an RR. Which statement is MOST accurate?",["The firm has recordkeeping and potentially reporting obligations","The complaint can be ignored unless damages exceed $1 million","Only the customer must retain it","It automatically becomes a SIPC claim"],"The firm has recordkeeping and potentially reporting obligations","Written complaints trigger firm recordkeeping and may trigger reporting duties.","Customer Complaint"),
("Which public FINRA resource allows investors to review registration and disclosure information about brokers and firms?",["BrokerCheck","DTCC","OCC","EDGAR only"],"BrokerCheck","BrokerCheck provides public registration and disclosure information.","BrokerCheck"),
("A registered person's reportable information changes while employed. Which statement is MOST accurate?",["Form U4 may need to be amended within applicable time requirements","Nothing is updated until Form U5","Only the customer updates the record","BrokerCheck automatically changes without firm action"],"Form U4 may need to be amended within applicable time requirements","U4 information must be kept current when reportable events occur.","U4 Update")],
19:[
("A bond yields 6% nominally while inflation is 2%. The approximate real interest rate is:",["2%","4%","6%","8%"],"4%","Real rate is approximately nominal rate minus inflation = 4%.","Real Interest Rate"),
("Which sequence correctly orders the standard business-cycle phases?",["expansion, peak, contraction, trough","peak, expansion, trough, contraction","contraction, expansion, peak, trough","trough, contraction, peak, expansion"],"expansion, peak, contraction, trough","That is the standard cycle sequence used in the manual.","Expansion"),
("The Federal Reserve buys government securities in the open market. All else equal, this action is generally intended to:",["add reserves/liquidity and put downward pressure on rates","remove reserves and force rates higher","reduce the money supply automatically","increase corporate tax rates"],"add reserves/liquidity and put downward pressure on rates","Fed purchases inject reserves; sales withdraw reserves.","Open Market Operations"),
("A yield curve has short-term yields above long-term yields. The curve is:",["inverted","normal","flat by definition","a credit spread"],"inverted","An inverted curve slopes downward with shorter rates above longer rates.","Inverted Yield Curve"),
("Which financial statement presents assets, liabilities and shareholders' equity at a point in time?",["balance sheet","income statement","cash confirmation","prospectus only"],"balance sheet","The balance sheet is a snapshot; the income statement covers a period.","Balance Sheet"),
("A company has 10 million outstanding common shares trading at $25. Its market capitalization is:",["$25 million","$250 million","$2.5 billion","$10 million"],"$250 million","Market capitalization = shares outstanding × market price = $250 million.","Market Capitalization")],
20:[
("An investor owns 30 stocks across unrelated industries. Which risk can diversification reduce MOST effectively?",["unsystematic/company-specific risk","broad market risk","inflation risk entirely","interest-rate risk entirely"],"unsystematic/company-specific risk","Diversification reduces issuer-specific risk but cannot eliminate broad systematic risk.","Unsystematic Risk"),
("A bond has a long duration. What does that MOST directly suggest?",["greater sensitivity to interest-rate changes","greater voting power","lower credit risk automatically","guaranteed liquidity"],"greater sensitivity to interest-rate changes","Duration measures interest-rate sensitivity.","Duration"),
("A stock has a beta of 1.4. Which interpretation is MOST appropriate?",["It has historically shown greater market-relative volatility than a beta-1 security","It has no systematic risk","It is guaranteed to outperform by 40%","Its duration is 1.4 years"],"It has historically shown greater market-relative volatility than a beta-1 security","Beta measures market-relative volatility/systematic exposure, not guaranteed return.","Beta"),
("A company-specific product recall damages one issuer while the broad market is stable. This is MOST closely an example of:",["unsystematic/business risk","systematic market risk only","inflation risk","interest-rate risk"],"unsystematic/business risk","The event is specific to the issuer and is diversifiable.","Business Risk"),
("A portfolio manager temporarily overweights defensive sectors because of an economic outlook, deviating from long-term target weights. This is MOST closely:",["tactical asset allocation","strategic asset allocation only","indexing","buy-and-hold"],"tactical asset allocation","Tactical allocation makes shorter-term deviations from strategic targets.","Tactical Asset Allocation"),
("A U.S. importer must pay euros in the future and is concerned the euro will rise. Which hedge described in the manual is MOST consistent with that risk?",["buy euro calls","buy U.S. dollar calls on a U.S. dollar option contract","sell euro calls only","buy a municipal revenue bond"],"buy euro calls","Euro calls increase in value if the euro rises, offsetting higher dollar cost of the euro-denominated payment.","Currency Risk")]
}

PREFIXES=[
"A registered representative is reviewing the following situation. ",
"Consider the following customer or market fact pattern. ",
"For SIE purposes, evaluate this situation. ",
"A securities professional encounters the following facts. ",
]

def expanded_scenarios(ch, variants=5):
    out=[]
    for idx,item in enumerate(SCENARIOS.get(ch,[])):
        q,choices,answer,why,term=item
        for v in range(variants):
            stem=q if v==0 else PREFIXES[(idx+v)%len(PREFIXES)]+q
            c=list(choices); random.shuffle(c)
            out.append({"q":stem,"c":c,"a":answer,"why":why,"chapter":ch,"term":term,"style":"application"})
    return out
